# Generated by Django 4.1.5 on 2023-03-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_timesheet"),
        ("authentication", "0003_alter_timesheet_employee"),
    ]

    operations = []
