# Generated by Django 4.1.5 on 2023-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_merge_0002_timesheet_0003_alter_timesheet_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="employee",
            field=models.TextField(max_length=50),
        ),
    ]
