# Generated by Django 4.1.5 on 2023-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_taskmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="teacher",
            field=models.CharField(max_length=250),
        ),
    ]
