# Generated by Django 4.1.5 on 2023-03-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_taskmodel_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=250)),
                ("student", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
    ]
